/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => YoutubeEssayPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var VALID_CLAUDE_MODELS = [
  "claude-opus-4-8",
  "claude-sonnet-4-6",
  "claude-haiku-4-5-20251001"
];
var VALID_OPENAI_MODELS = [
  "gpt-5.5",
  "gpt-5.4",
  "gpt-5.4-mini",
  "gpt-4o",
  "gpt-4o-mini"
];
var VALID_GEMINI_MODELS = [
  "gemini-3.5-flash",
  "gemini-2.5-pro",
  "gemini-2.5-flash",
  "gemini-2.5-flash-lite"
  // gemini-2.0-flash 및 2.0-flash-lite 는 단종 — 목록에서 제거해 마이그레이션 강제 적용
];
var DEFAULT_SETTINGS = {
  apiProvider: "claude",
  claudeApiKey: "",
  claudeModel: "claude-haiku-4-5-20251001",
  openaiApiKey: "",
  openaiModel: "gpt-5.4-mini",
  geminiApiKey: "",
  geminiModel: "gemini-2.5-flash",
  outputFolder: "Essays",
  defaultLanguage: "ko",
  defaultQuality: "balanced"
};
function migrateSettings(s) {
  if (!VALID_CLAUDE_MODELS.includes(s.claudeModel))
    s.claudeModel = DEFAULT_SETTINGS.claudeModel;
  if (!VALID_OPENAI_MODELS.includes(s.openaiModel))
    s.openaiModel = DEFAULT_SETTINGS.openaiModel;
  if (!VALID_GEMINI_MODELS.includes(s.geminiModel))
    s.geminiModel = DEFAULT_SETTINGS.geminiModel;
  return s;
}
var YoutubeEssaySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "YouTube Essay Generator" });
    containerEl.createEl("h3", { text: "\uC0AC\uC6A9\uD560 AI \uC81C\uACF5\uC790 / Active Provider" });
    new import_obsidian.Setting(containerEl).setName("Active Provider").setDesc("\uC5D0\uC138\uC774 \uC0DD\uC131\uC5D0 \uC0AC\uC6A9\uD560 AI \uC11C\uBE44\uC2A4\uB97C \uC120\uD0DD\uD558\uC138\uC694").addDropdown(
      (drop) => drop.addOption("claude", "\u{1F7E0} Claude (Anthropic)").addOption("openai", "\u{1F7E2} OpenAI (GPT)").addOption("gemini", "\u{1F535} Gemini (Google)").setValue(this.plugin.settings.apiProvider).onChange(async (value) => {
        this.plugin.settings.apiProvider = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F7E0} Claude (Anthropic)" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("console.anthropic.com \u2192 API Keys").addText((text) => {
      text.setPlaceholder("sk-ant-\u2026").setValue(this.plugin.settings.claudeApiKey).onChange(async (v) => {
        this.plugin.settings.claudeApiKey = v.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      text.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(containerEl).setName("Model").addDropdown(
      (drop) => drop.addOption("claude-opus-4-8", "Opus 4.8 \u2014 \uCD5C\uACE0 \uD488\uC9C8").addOption("claude-sonnet-4-6", "Sonnet 4.6 \u2014 \uADE0\uD615").addOption("claude-haiku-4-5-20251001", "Haiku 4.5 \u2014 \uBE60\uB984 / \uC800\uB834").setValue(this.plugin.settings.claudeModel).onChange(async (v) => {
        this.plugin.settings.claudeModel = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F7E2} OpenAI (GPT)" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("platform.openai.com \u2192 API Keys").addText((text) => {
      text.setPlaceholder("sk-\u2026").setValue(this.plugin.settings.openaiApiKey).onChange(async (v) => {
        this.plugin.settings.openaiApiKey = v.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      text.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(containerEl).setName("Model").addDropdown(
      (drop) => drop.addOption("gpt-5.5", "GPT-5.5 \u2014 \uCD5C\uACE0 \uD488\uC9C8").addOption("gpt-5.4", "GPT-5.4 \u2014 \uADE0\uD615").addOption("gpt-5.4-mini", "GPT-5.4 mini \u2014 \uBE60\uB984 / \uC800\uB834").addOption("gpt-4o", "GPT-4o \u2014 \uAD6C\uBC84\uC804").addOption("gpt-4o-mini", "GPT-4o mini \u2014 \uAD6C\uBC84\uC804").setValue(this.plugin.settings.openaiModel).onChange(async (v) => {
        this.plugin.settings.openaiModel = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F535} Gemini (Google)" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("aistudio.google.com \u2192 Get API Key").addText((text) => {
      text.setPlaceholder("AIza\u2026").setValue(this.plugin.settings.geminiApiKey).onChange(async (v) => {
        this.plugin.settings.geminiApiKey = v.trim();
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
      text.inputEl.style.width = "100%";
    });
    new import_obsidian.Setting(containerEl).setName("Model").addDropdown(
      (drop) => drop.addOption("gemini-3.5-flash", "Gemini 3.5 Flash \u2014 \uCD5C\uC2E0").addOption("gemini-2.5-pro", "Gemini 2.5 Pro \u2014 \uCD5C\uACE0 \uD488\uC9C8").addOption("gemini-2.5-flash", "Gemini 2.5 Flash \u2014 \uADE0\uD615").addOption("gemini-2.5-flash-lite", "Gemini 2.5 Flash-Lite \u2014 \uC800\uB834").setValue(this.plugin.settings.geminiModel).onChange(async (v) => {
        this.plugin.settings.geminiModel = v;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\uC77C\uBC18 \uC124\uC815 / General" });
    new import_obsidian.Setting(containerEl).setName("Default Language / Style").setDesc("\uC0DD\uC131 \uC2DC \uBAA8\uB2EC\uC5D0\uC11C \uC5B8\uC81C\uB4E0 \uBCC0\uACBD \uAC00\uB2A5").addDropdown(
      (drop) => drop.addOption("ko", "\uD55C\uAD6D\uC5B4 \u2014 \uB274\uD544\uB85C\uC18C\uD37C \uC2A4\uD0C0\uC77C").addOption("en", "English \u2014 AEON style").setValue(this.plugin.settings.defaultLanguage).onChange(async (v) => {
        this.plugin.settings.defaultLanguage = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default Quality / Cost").setDesc(
      "\uC800\uBE44\uC6A9: \uBE60\uB974\uACE0 \uC800\uB834 | \uC911\uAC04: \uADE0\uD615 (\uAD8C\uC7A5) | \uACE0\uD488\uC9C8: \uAC00\uC7A5 \uC0C1\uC138\uD558\uC9C0\uB9CC \uD1A0\uD070 \uC18C\uBAA8 \uD07C"
    ).addDropdown(
      (drop) => drop.addOption("quick", "\u26A1 \uC800\uBE44\uC6A9 \u2014 \uC9E7\uC740 \uC601\uC0C1\xB7\uBE44\uC6A9 \uC808\uAC10").addOption("balanced", "\u2696\uFE0F \uC911\uAC04\uBE44\uC6A9 \u2014 \uADE0\uD615 (\uAE30\uBCF8\uAC12)").addOption("thorough", "\u{1F50D} \uACE0\uD488\uC9C8 \u2014 \uAE34 \uC601\uC0C1\xB7\uC0C1\uC138 \uCEE4\uBC84\uB9AC\uC9C0").setValue(this.plugin.settings.defaultQuality).onChange(async (v) => {
        this.plugin.settings.defaultQuality = v;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Output Folder").setDesc("\uC5D0\uC138\uC774\uAC00 \uC800\uC7A5\uB420 Vault \uD3F4\uB354 (\uC5C6\uC73C\uBA74 \uC790\uB3D9 \uC0DD\uC131)").addText(
      (text) => text.setPlaceholder("Essays").setValue(this.plugin.settings.outputFolder).onChange(async (v) => {
        this.plugin.settings.outputFolder = v.trim();
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/modal.ts
var import_obsidian3 = require("obsidian");

// src/essay.ts
var import_obsidian2 = require("obsidian");
var QUALITY_PARAMS = {
  quick: {
    excerptMaxChars: 5e3,
    overlapRatio: 0,
    // no overlap — overlap causes duplicate content
    chunkSummaryTokens: 500,
    outlineMaxTokens: 2048,
    maxSections: 5,
    sectionOutputTokens: 2500
  },
  balanced: {
    excerptMaxChars: 7500,
    overlapRatio: 0,
    chunkSummaryTokens: 700,
    outlineMaxTokens: 3e3,
    maxSections: 8,
    sectionOutputTokens: 5e3
  },
  thorough: {
    excerptMaxChars: 1e4,
    overlapRatio: 0,
    chunkSummaryTokens: 900,
    outlineMaxTokens: 4096,
    maxSections: 12,
    sectionOutputTokens: 0
    // 0 = use model max
  }
};
function chunkText(text, maxChars = 24e3) {
  var _a;
  if (text.length <= maxChars) return [text];
  const chunks = [];
  const sentences = (_a = text.match(/[^.!?。！？\n]+[.!?。！？\n]+/g)) != null ? _a : [text];
  let current = "";
  for (const sentence of sentences) {
    if ((current + sentence).length > maxChars && current.length > 0) {
      chunks.push(current.trim());
      current = sentence;
    } else {
      current += " " + sentence;
    }
  }
  if (current.trim()) chunks.push(current.trim());
  return chunks;
}
function parseOutline(raw) {
  const getField = (...keys) => {
    var _a;
    for (const key of keys) {
      const re = new RegExp(`${key}\\s*::?\\s*(.+)`, "i");
      const m2 = raw.match(re);
      if ((_a = m2 == null ? void 0 : m2[1]) == null ? void 0 : _a.trim()) return m2[1].trim();
    }
    return "";
  };
  const essayTitle = getField("TITLE", "ESSAY_TITLE", "ESSAY TITLE");
  const introduction = getField("INTRO", "INTRODUCTION");
  const conclusion = getField("CONCLUSION", "CLOSING");
  const titles = {};
  const summaries = {};
  const titleRe = /SECTION[_\s]?(\d+)[_\s]?TITLE\s*::?\s*(.+)/gi;
  const summaryRe = /SECTION[_\s]?(\d+)[_\s]?(SUMMARY|DESC|요약|내용)\s*::?\s*(.+)/gi;
  let m;
  while ((m = titleRe.exec(raw)) !== null) titles[+m[1]] = m[2].trim();
  while ((m = summaryRe.exec(raw)) !== null) summaries[+m[1]] = m[3].trim();
  const sections = Object.keys(titles).map(Number).sort((a, b) => a - b).map((n) => {
    var _a;
    return { title: titles[n], summary: (_a = summaries[n]) != null ? _a : "" };
  });
  if (!essayTitle || sections.length === 0) {
    throw new Error(
      `Could not parse outline.
Raw response (first 600 chars):
${raw.slice(0, 600)}`
    );
  }
  return { essayTitle, introduction, sections, conclusion };
}
var MODEL_MAX_OUTPUT = {
  // Claude
  "claude-opus-4-8": 16e3,
  "claude-sonnet-4-6": 16e3,
  "claude-haiku-4-5-20251001": 8192,
  // OpenAI — GPT-5 계열
  "gpt-5.5": 16384,
  "gpt-5.4": 16384,
  "gpt-5.4-mini": 16384,
  "gpt-5.4-nano": 16384,
  // OpenAI — 구버전
  "gpt-4o": 16384,
  "gpt-4o-mini": 16384,
  "gpt-4.1": 32768,
  "gpt-4.1-mini": 32768,
  // Gemini
  "gemini-3.5-flash": 8192,
  "gemini-2.5-pro": 8192,
  "gemini-2.5-flash": 8192,
  "gemini-2.5-flash-lite": 8192,
  "gemini-2.0-flash": 8192,
  "gemini-2.0-flash-lite": 8192
};
function clampTokens(cfg, requested) {
  var _a;
  const modelMax = (_a = MODEL_MAX_OUTPUT[cfg.model]) != null ? _a : 4096;
  return Math.min(requested, modelMax);
}
async function llmCall(config, system, user, maxTokens = 2e3) {
  const clamped = clampTokens(config, maxTokens);
  switch (config.provider) {
    case "claude":
      return callClaude(config, system, user, clamped);
    case "openai":
      return callOpenAI(config, system, user, clamped);
    case "gemini":
      return callGemini(config, system, user, clamped);
  }
}
function apiError(provider, model, status, body) {
  var _a, _b;
  const msg = (_b = (_a = body == null ? void 0 : body.error) == null ? void 0 : _a.message) != null ? _b : JSON.stringify(body).slice(0, 200);
  return new Error(`[${provider}] ${status} \u2014 model: ${model}
${msg}`);
}
async function callClaude(cfg, system, user, maxTokens) {
  var _a, _b, _c, _d;
  const resp = await (0, import_obsidian2.requestUrl)({
    url: "https://api.anthropic.com/v1/messages",
    method: "POST",
    throw: false,
    headers: {
      "x-api-key": cfg.apiKey,
      "anthropic-version": "2023-06-01",
      "content-type": "application/json"
    },
    body: JSON.stringify({
      model: cfg.model,
      max_tokens: maxTokens,
      system,
      messages: [{ role: "user", content: user }]
    })
  });
  if (resp.status !== 200) throw apiError("Claude", cfg.model, resp.status, resp.json);
  const text = (_c = (_b = (_a = resp.json) == null ? void 0 : _a.content) == null ? void 0 : _b[0]) == null ? void 0 : _c.text;
  if (!text) throw new Error(`[Claude] Empty response. stop_reason: ${(_d = resp.json) == null ? void 0 : _d.stop_reason}`);
  return text;
}
async function callOpenAI(cfg, system, user, maxTokens) {
  var _a, _b, _c, _d, _e, _f, _g;
  const resp = await (0, import_obsidian2.requestUrl)({
    url: "https://api.openai.com/v1/chat/completions",
    method: "POST",
    throw: false,
    headers: { Authorization: `Bearer ${cfg.apiKey}`, "content-type": "application/json" },
    body: JSON.stringify({
      model: cfg.model,
      max_completion_tokens: maxTokens,
      messages: [
        { role: "system", content: system },
        { role: "user", content: user }
      ]
    })
  });
  if (resp.status !== 200) throw apiError("OpenAI", cfg.model, resp.status, resp.json);
  const text = (_d = (_c = (_b = (_a = resp.json) == null ? void 0 : _a.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content;
  if (!text) throw new Error(`[OpenAI] Empty response. finish_reason: ${(_g = (_f = (_e = resp.json) == null ? void 0 : _e.choices) == null ? void 0 : _f[0]) == null ? void 0 : _g.finish_reason}`);
  return text;
}
async function callGemini(cfg, system, user, maxTokens) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  const resp = await (0, import_obsidian2.requestUrl)({
    url: `https://generativelanguage.googleapis.com/v1beta/models/${cfg.model}:generateContent?key=${cfg.apiKey}`,
    method: "POST",
    throw: false,
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      system_instruction: { parts: [{ text: system }] },
      contents: [{ role: "user", parts: [{ text: user }] }],
      generationConfig: {
        maxOutputTokens: maxTokens,
        // Prevent safety blocks from terminating mid-generation
        stopSequences: []
      }
    })
  });
  if (resp.status !== 200) throw apiError("Gemini", cfg.model, resp.status, resp.json);
  const candidates = (_a = resp.json) == null ? void 0 : _a.candidates;
  if (!(candidates == null ? void 0 : candidates.length)) {
    const blockReason = (_d = (_c = (_b = resp.json) == null ? void 0 : _b.promptFeedback) == null ? void 0 : _c.blockReason) != null ? _d : "unknown";
    throw new Error(`[Gemini] No candidates returned. Block reason: ${blockReason}`);
  }
  const candidate = candidates[0];
  const finishReason = (_e = candidate == null ? void 0 : candidate.finishReason) != null ? _e : "";
  const text = (_i = (_h = (_g = (_f = candidate == null ? void 0 : candidate.content) == null ? void 0 : _f.parts) == null ? void 0 : _g[0]) == null ? void 0 : _h.text) != null ? _i : "";
  if (!text) {
    throw new Error(`[Gemini] Empty content. Finish reason: ${finishReason}`);
  }
  if (finishReason === "MAX_TOKENS") {
    console.warn(`[Gemini] Section hit MAX_TOKENS \u2014 returned partial content`);
  }
  return text;
}
var AEON_SYSTEM = `You are a staff writer for Aeon Magazine. Your task is to retell the ideas in a video transcript in Aeon's distinctive voice \u2014 literary, unhurried, intellectually curious.

Rules:
- Follow the video's own logic and sequence of ideas. Do not invent a new argument structure.
- Cover ALL the ideas in your assigned transcript excerpt. Do not skip or compress content \u2014 if the video spent time on it, the essay must too.
- Never repeat a point already made in a previous section.
- Ground abstract ideas in concrete human experience. Use vivid prose, not academic summary.
- Subheadings should be evocative phrases that reflect what the section actually covers, not generic labels.
- Write as much as the content requires \u2014 a long video deserves a long essay. Do not cut ideas short.`;
var NYPHILOSOPHER_SYSTEM = `\uB2F9\uC2E0\uC740 \u300A\uB274 \uD544\uB85C\uC18C\uD37C(New Philosopher)\u300B \uD55C\uAD6D\uC5B4\uD310 \uCCA0\uD559 \uC5D0\uC138\uC774 \uC791\uAC00\uC785\uB2C8\uB2E4.

\uC5ED\uD560: \uC601\uC0C1 \uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8\uC758 \uB0B4\uC6A9\uC744 \uB274\uD544\uB85C\uC18C\uD37C \uBB38\uCCB4\uB85C \uB2E4\uC2DC \uC4F0\uB294 \uAC83. \uB0B4\uC6A9\uC744 \uCC3D\uC791\uD558\uAC70\uB098 \uBD80\uD480\uB9AC\uB294 \uAC83\uC774 \uC544\uB2D9\uB2C8\uB2E4.

\uADDC\uCE59:
- \uC601\uC0C1\uC774 \uC804\uAC1C\uD558\uB294 \uB17C\uB9AC\uC640 \uD750\uB984\uC744 \uADF8\uB300\uB85C \uB530\uB974\uC138\uC694. \uC0C8\uB85C\uC6B4 \uB17C\uC99D \uAD6C\uC870\uB97C \uB9CC\uB4E4\uC9C0 \uB9C8\uC138\uC694.
- \uC774\uBBF8 \uB2E4\uB8EC \uB0B4\uC6A9\uC744 \uBC18\uBCF5\uD558\uC9C0 \uB9C8\uC138\uC694. \uC4F8 \uB0B4\uC6A9\uC774 \uC5C6\uC73C\uBA74 \uC5B5\uC9C0\uB85C \uB298\uB9AC\uC9C0 \uB9C8\uC138\uC694.
- \uCCA0\uD559\uC801 \uAC1C\uB150\uC744 \uAD6C\uCCB4\uC801 \uC7A5\uBA74\uC774\uB098 \uC9C8\uBB38\uC73C\uB85C \uC5F4\uB418, \uC601\uC0C1\uC5D0 \uC5C6\uB294 \uB0B4\uC6A9\uC744 \uCD94\uAC00\uD558\uC9C0 \uB9C8\uC138\uC694.
- \uC18C\uC81C\uBAA9\uC740 \uD574\uB2F9 \uC139\uC158\uC758 \uC2E4\uC81C \uB0B4\uC6A9\uC744 \uBC18\uC601\uD558\uB294 \uBA85\uC0C1\uC801\xB7\uC9C8\uBB38\uD615 \uBB38\uAD6C\uB85C \uC9D3\uB418, \uACFC\uC7A5\uD558\uC9C0 \uB9C8\uC138\uC694.
- \uBB38\uCCB4\uB294 \uC0AC\uBCC0\uC801\uC774\uACE0 \uC11C\uC815\uC801\uC774\uB418 \uB17C\uB9AC\uC801 \uD750\uB984\uC744 \uC783\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.`;
var SYS = (lang) => lang === "en" ? AEON_SYSTEM : NYPHILOSOPHER_SYSTEM;
async function buildOutline(cfg, transcript, lang, sourceTitle, qp, onStatus) {
  const chunks = chunkText(transcript, 24e3);
  let condensed = transcript;
  if (chunks.length > 1) {
    const summaries = [];
    for (let i = 0; i < chunks.length; i++) {
      onStatus(
        lang === "en" ? `Condensing transcript part ${i + 1}/${chunks.length}\u2026` : `\uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8 \uC694\uC57D \uC911 ${i + 1}/${chunks.length}\u2026`
      );
      const s = await llmCall(
        cfg,
        lang === "en" ? "You are a precise summariser. Preserve every distinct topic and argument so nothing is lost when the summary is used to write an essay." : "\uB2F9\uC2E0\uC740 \uC815\uD655\uD55C \uC694\uC57D \uC804\uBB38\uAC00\uC785\uB2C8\uB2E4. \uC774\uD6C4 \uC5D0\uC138\uC774 \uC791\uC131\uC5D0 \uC4F0\uC77C \uC694\uC57D\uC774\uBBC0\uB85C \uBAA8\uB4E0 \uAC1C\uBCC4 \uC8FC\uC81C\uC640 \uB17C\uC810\uC774 \uC190\uC2E4 \uC5C6\uC774 \uBCF4\uC874\uB418\uC5B4\uC57C \uD569\uB2C8\uB2E4.",
        lang === "en" ? `Summarise this transcript excerpt (part ${i + 1}/${chunks.length}). List every topic in order with enough detail to reconstruct the ideas later:

${chunks[i]}` : `\uB2E4\uC74C \uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8 \uC870\uAC01(${i + 1}/${chunks.length}\uBC88\uC9F8)\uC744 \uC21C\uC11C\uB300\uB85C, \uB098\uC911\uC5D0 \uC7AC\uAD6C\uC131 \uAC00\uB2A5\uD55C \uC218\uC900\uC73C\uB85C \uC694\uC57D\uD558\uC138\uC694:

${chunks[i]}`,
        qp.chunkSummaryTokens
      );
      summaries.push(s);
    }
    condensed = summaries.join("\n\n---\n\n");
  }
  onStatus(lang === "en" ? "Building essay outline\u2026" : "\uC5D0\uC138\uC774 \uAC1C\uC694 \uAD6C\uC131 \uC911\u2026");
  const prompt = lang === "en" ? `Read the transcript below and map it into an Aeon essay outline. The outline must mirror the VIDEO'S actual structure and sequence \u2014 do not invent themes or merge/skip distinct ideas.

Output ONLY lines in the format  KEY:: value  (one per line, no markdown, no extra text).

TITLE:: a literary essay title capturing the video's core idea
INTRO:: one sentence: the opening hook or scene
SECTION_1_TITLE:: evocative subheading for what the video covers first
SECTION_1_SUMMARY:: specific content this section covers (one sentence)
SECTION_2_TITLE:: ...
SECTION_2_SUMMARY:: ...
... (keep adding sections until ALL topics in the transcript are accounted for)
CONCLUSION:: one sentence: how the essay closes

How many sections: decide based on how many distinct topics the video covers. A 10-minute video might need 3\u20134 sections. A 30-minute video typically needs 6\u20138. A 60-minute video may need 10 or more. Never merge unrelated topics into one section just to reduce the count. Every major idea in the transcript must appear in a section summary.

TRANSCRIPT:
${condensed}` : `\uC601\uC0C1 "${sourceTitle}"\uC758 \uC2E4\uC81C \uC804\uAC1C \uD750\uB984\uC744 \uC5D0\uC138\uC774 \uAC1C\uC694\uB85C \uC62E\uAE30\uC138\uC694. \uC601\uC0C1\uC5D0 \uC5C6\uB294 \uC0C8\uB85C\uC6B4 \uC139\uC158\uC774\uB098 \uC8FC\uC81C\uB97C \uB9CC\uB4E4\uC9C0 \uB9C8\uC138\uC694.

\uBC18\uB4DC\uC2DC \uC544\uB798 \uD615\uC2DD\uC73C\uB85C\uB9CC \uCD9C\uB825\uD558\uC138\uC694. \uAC01 \uC904\uC740  \uD0A4:: \uAC12  \uD615\uD0DC. \uB9C8\uD06C\uB2E4\uC6B4\xB7JSON\xB7\uCD94\uAC00 \uD14D\uC2A4\uD2B8 \uC5C6\uC774:

TITLE:: \uC601\uC0C1\uC758 \uD575\uC2EC \uC544\uC774\uB514\uC5B4\uB97C \uB2F4\uC740 \uCCA0\uD559\uC801\xB7\uC2DC\uC801 \uC81C\uBAA9
INTRO:: \uC11C\uB450 \uC7A5\uBA74/\uC9C8\uBB38 (\uD55C \uBB38\uC7A5, \uC601\uC0C1 \uB0B4\uC6A9 \uAE30\uBC18)
SECTION_1_TITLE:: \uC601\uC0C1\uC774 \uC2E4\uC81C\uB85C \uBA3C\uC800 \uB2E4\uB8E8\uB294 \uB0B4\uC6A9\uC744 \uBC18\uC601\uD55C \uC18C\uC81C\uBAA9
SECTION_1_SUMMARY:: \uC774 \uC139\uC158 \uB0B4\uC6A9 (\uD55C \uBB38\uC7A5, \uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8 \uAE30\uBC18)
SECTION_2_TITLE:: ...
SECTION_2_SUMMARY:: ...
(\uC601\uC0C1\uC758 \uC790\uC5F0\uC2A4\uB7EC\uC6B4 \uAD6C\uC870\uC5D0 \uB9DE\uAC8C \uC139\uC158 \uC218 \uACB0\uC815 \u2014 \uBCF4\uD1B5 3\u20136\uAC1C)
CONCLUSION:: \uC5D0\uC138\uC774 \uB9C8\uBB34\uB9AC \uBC29\uD5A5 (\uD55C \uBB38\uC7A5)

\uC139\uC158 \uC218\uB294 \uC601\uC0C1 \uB0B4\uC6A9\uC774 \uC2E4\uC81C\uB85C \uC694\uAD6C\uD558\uB294 \uB9CC\uD07C\uB9CC \uC0AC\uC6A9\uD558\uC138\uC694. \uBD84\uB7C9 \uCC44\uC6B0\uAE30\uC6A9 \uC139\uC158 \uCD94\uAC00 \uAE08\uC9C0.

\uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8:
${condensed}`;
  const raw = await llmCall(cfg, SYS(lang), prompt, qp.outlineMaxTokens);
  const outline = parseOutline(raw);
  if (outline.sections.length > qp.maxSections) {
    outline.sections = outline.sections.slice(0, qp.maxSections);
  }
  return outline;
}
async function writeSection(cfg, lang, outline, index, fullTranscript, completedSections, qp) {
  var _a;
  const section = outline.sections[index];
  const n = outline.sections.length;
  const start = Math.floor(index / n * fullTranscript.length);
  const end = Math.min(
    Math.floor((index + 1) / n * fullTranscript.length),
    start + qp.excerptMaxChars
  );
  const excerpt = fullTranscript.slice(start, end);
  const alreadyCovered = completedSections.length > 0 ? completedSections.map((s, i) => `- Section ${i + 1} "${s.title}": ${s.summary}`).join("\n") : null;
  const prompt = lang === "en" ? `You are writing section ${index + 1} of ${n} for the Aeon essay titled "${outline.essayTitle}".

TOPICS ALREADY COVERED IN PREVIOUS SECTIONS \u2014 DO NOT REPEAT THESE:
${alreadyCovered != null ? alreadyCovered : "(this is the first section \u2014 nothing covered yet)"}

CURRENT SECTION: "${section.title}"
${index === 0 ? "Open with a vivid hook \u2014 a scene, anecdote, or provocative question." : "Pick up where the previous section left off. Do not re-introduce topics listed above."}

Your job: rewrite ONLY the transcript excerpt below in Aeon's literary voice.
- Treat your excerpt as a strict boundary: only write about what appears here.
- If the excerpt mentions a topic already covered above, skip it entirely.
- Cover every NEW idea in the excerpt fully \u2014 do not compress or omit.
- Output body text ONLY (no heading). Every sentence must be complete.

TRANSCRIPT EXCERPT (your sole source \u2014 section ${index + 1} of ${n}):
${excerpt}` : `\uB274\uD544\uB85C\uC18C\uD37C \uC5D0\uC138\uC774 "${outline.essayTitle}"\uC758 ${index + 1}\uBC88\uC9F8 \uC139\uC158(\uC804\uCCB4 ${n}\uAC1C)\uC744 \uC791\uC131\uD569\uB2C8\uB2E4.

\uC774\uC804 \uC139\uC158\uC5D0\uC11C \uC774\uBBF8 \uB2E4\uB8EC \uC8FC\uC81C \u2014 \uC808\uB300 \uBC18\uBCF5 \uAE08\uC9C0:
${alreadyCovered != null ? alreadyCovered : "(\uCCAB \uBC88\uC9F8 \uC139\uC158 \u2014 \uC544\uC9C1 \uB2E4\uB8EC \uB0B4\uC6A9 \uC5C6\uC74C)"}

\uD604\uC7AC \uC139\uC158: "${section.title}"
${index === 0 ? "\uC77C\uC0C1\uC758 \uC7A5\uBA74\uC774\uB098 \uCCA0\uD559\uC801 \uC9C8\uBB38\uC73C\uB85C \uC5D0\uC138\uC774\uB97C \uC5EC\uC138\uC694." : "\uC774\uC804 \uC139\uC158\uC5D0\uC11C \uC790\uC5F0\uC2A4\uB7FD\uAC8C \uC774\uC5B4\uC9C0\uC138\uC694. \uC704\uC5D0 \uB098\uC5F4\uB41C \uC8FC\uC81C\uB294 \uB2E4\uC2DC \uAEBC\uB0B4\uC9C0 \uB9C8\uC138\uC694."}

\uC544\uB798 \uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8 \uB0B4\uC6A9\uB9CC \uB274\uD544\uB85C\uC18C\uD37C \uBB38\uCCB4\uB85C \uB2E4\uC2DC \uC4F0\uC138\uC694.
- \uC774 \uBC1C\uCDCC\uBB38\uC744 \uC5C4\uACA9\uD55C \uACBD\uACC4\uB85C \uCDE8\uAE09\uD558\uC138\uC694. \uC5EC\uAE30 \uB098\uC628 \uB0B4\uC6A9\uB9CC \uC4F0\uC138\uC694.
- \uBC1C\uCDCC\uBB38\uC5D0 \uC704\uC758 '\uC774\uBBF8 \uB2E4\uB8EC \uC8FC\uC81C'\uAC00 \uB4F1\uC7A5\uD558\uBA74 \uADF8 \uBD80\uBD84\uC740 \uAC74\uB108\uB6F0\uC138\uC694.
- \uBC1C\uCDCC\uBB38\uC758 \uC0C8\uB85C\uC6B4 \uB0B4\uC6A9\uC740 \uBE60\uC9D0\uC5C6\uC774 \uCDA9\uBD84\uD788 \uB2E4\uB8E8\uC138\uC694.
- \uC18C\uC81C\uBAA9 \uC5C6\uC774 \uBCF8\uBB38\uB9CC \uCD9C\uB825\uD558\uC138\uC694. \uBC18\uB4DC\uC2DC \uB9C8\uC9C0\uB9C9 \uBB38\uC7A5\uC744 \uC644\uC804\uD788 \uB05D\uB0B4\uC138\uC694.

\uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8 \uBC1C\uCDCC (\uC774 \uC139\uC158\uC758 \uC720\uC77C\uD55C \uC18C\uC2A4 \u2014 ${n}\uAC1C \uC911 ${index + 1}\uBC88\uC9F8):
${excerpt}`;
  const modelMax = (_a = MODEL_MAX_OUTPUT[cfg.model]) != null ? _a : 4096;
  const outTokens = qp.sectionOutputTokens > 0 ? Math.min(qp.sectionOutputTokens, modelMax) : modelMax;
  return (await llmCall(cfg, SYS(lang), prompt, outTokens)).trim();
}
async function writeIntroOrConclusion(cfg, lang, outline, bodyText, type) {
  const prompt = lang === "en" ? type === "introduction" ? `Write the opening paragraph(s) for the Aeon essay "${outline.essayTitle}".
Direction: ${outline.introduction}
Hook the reader with a scene or question. Establish the essay's intellectual direction. Do not summarise what follows \u2014 just open the door.
Output introduction text ONLY. End every sentence completely.` : `Write the closing paragraph(s) for the Aeon essay "${outline.essayTitle}".
Direction: ${outline.conclusion}
Do NOT summarise the essay. Return to the opening image or question if possible, then open onto a wider horizon. Leave the reader with something to think about.

ESSAY BODY (final portion):
${bodyText.slice(-2e3)}

Output conclusion text ONLY. End every sentence completely.` : type === "introduction" ? `\uC5D0\uC138\uC774 "${outline.essayTitle}"\uC758 \uC11C\uB860\uC744 \uC791\uC131\uD558\uC138\uC694.
\uBC29\uD5A5: ${outline.introduction}
\uB3C5\uC790\uB97C \uB04C\uC5B4\uB4E4\uC774\uB294 \uC7A5\uBA74\uC774\uB098 \uC9C8\uBB38\uC73C\uB85C \uC2DC\uC791\uD558\uACE0 \uC5D0\uC138\uC774\uC758 \uC0AC\uC720 \uBC29\uD5A5\uC744 \uC554\uC2DC\uD558\uC138\uC694. \uBCF8\uBB38\uC744 \uC694\uC57D\uD558\uC9C0 \uB9C8\uC138\uC694 \u2014 \uADF8\uB0E5 \uBB38\uC744 \uC5F4\uBA74 \uB429\uB2C8\uB2E4.
\uC11C\uB860 \uBCF8\uBB38\uB9CC \uCD9C\uB825\uD558\uC138\uC694. \uBC18\uB4DC\uC2DC \uC644\uC804\uD55C \uBB38\uC7A5\uC73C\uB85C \uB9C8\uBB34\uB9AC\uD558\uC138\uC694.` : `\uC5D0\uC138\uC774 "${outline.essayTitle}"\uC758 \uACB0\uB860\uC744 \uC791\uC131\uD558\uC138\uC694.
\uBC29\uD5A5: ${outline.conclusion}
\uBCF8\uBB38\uC744 \uC694\uC57D\uD558\uC9C0 \uB9C8\uC138\uC694. \uAC00\uB2A5\uD558\uBA74 \uC11C\uB450\uC758 \uC774\uBBF8\uC9C0\uB098 \uC9C8\uBB38\uC73C\uB85C \uB3CC\uC544\uC624\uBA70 \uB354 \uD070 \uC9C0\uD3C9\uC744 \uC5F4\uC5B4 \uB9C8\uBB34\uB9AC\uD558\uC138\uC694.

\uBCF8\uBB38 \uB9C8\uC9C0\uB9C9 \uBD80\uBD84:
${bodyText.slice(-2e3)}

\uACB0\uB860 \uBCF8\uBB38\uB9CC \uCD9C\uB825\uD558\uC138\uC694. \uBC18\uB4DC\uC2DC \uC644\uC804\uD55C \uBB38\uC7A5\uC73C\uB85C \uB9C8\uBB34\uB9AC\uD558\uC138\uC694.`;
  return (await llmCall(cfg, SYS(lang), prompt, 2e3)).trim();
}
async function deduplicateBody(cfg, lang, sectionsWithHeadings) {
  var _a;
  const fullBody = sectionsWithHeadings.map((s, i) => `=== SECTION ${i + 1}: ${s.heading} ===
${s.body}`).join("\n\n");
  if (fullBody.length < 1500) {
    return sectionsWithHeadings.map((s) => s.body);
  }
  const prompt = lang === "en" ? `The essay body below is divided into sections. Read all sections first, then remove duplicate content.

A duplicate means: the SAME IDEA, argument, or historical fact \u2014 even if worded differently. Examples of what counts as duplicate:
- Section 2 explains Martin Luther's Reformation after Section 1 already did
- Section 3 quotes Rousseau's "man is born free" after Section 2 already referenced it
- Any section re-introduces a concept (liberalism, identity, the Declaration of Independence) already established earlier

Rules:
- Keep the FIRST occurrence. Delete all later repetitions of the same idea.
- Do not rewrite or rephrase \u2014 only delete sentences or paragraphs.
- Keep section markers (=== SECTION N: ... ===) intact.
- If a section becomes empty, write "(content moved to earlier section)" as placeholder.
- Output the complete text with markers.

ESSAY BODY:
${fullBody}` : `\uC544\uB798 \uC5D0\uC138\uC774 \uBCF8\uBB38\uC744 \uC139\uC158\uBCC4\uB85C \uC77D\uACE0, \uC55E \uC139\uC158\uC5D0\uC11C \uC774\uBBF8 \uB2E4\uB8EC \uC544\uC774\uB514\uC5B4\uB97C \uBC18\uBCF5\uD558\uB294 \uB0B4\uC6A9\uC744 \uC0AD\uC81C\uD558\uC138\uC694.

\uC911\uBCF5\uC758 \uAE30\uC900: \uD45C\uD604\uC774 \uB2EC\uB77C\uB3C4 \uAC19\uC740 \uC544\uC774\uB514\uC5B4\xB7\uB17C\uC810\xB7\uC5ED\uC0AC\uC801 \uC0AC\uC2E4\uC774\uBA74 \uC911\uBCF5\uC785\uB2C8\uB2E4. \uC608\uC2DC:
- 2\uBC88\uC9F8 \uC139\uC158\uC774 1\uBC88\uC9F8 \uC139\uC158\uC5D0\uC11C \uC774\uBBF8 \uC124\uBA85\uD55C \uB8E8\uD130\uC758 \uC885\uAD50\uAC1C\uD601\uC744 \uB2E4\uC2DC \uC124\uBA85
- 3\uBC88\uC9F8 \uC139\uC158\uC774 2\uBC88\uC9F8 \uC139\uC158\uC5D0\uC11C \uC774\uBBF8 \uC778\uC6A9\uD55C \uB8E8\uC18C\uC758 "\uC778\uAC04\uC740 \uC790\uC720\uB86D\uAC8C \uD0DC\uC5B4\uB09C\uB2E4"\uB97C \uB2E4\uC2DC \uC778\uC6A9
- \uC5B4\uB5A4 \uC139\uC158\uC774\uB4E0 \uC55E\uC5D0\uC11C \uC774\uBBF8 \uD655\uB9BD\uB41C \uAC1C\uB150(\uC790\uC720\uC8FC\uC758, \uC815\uCCB4\uC131, \uB3C5\uB9BD\uC120\uC5B8\uC11C \uB4F1)\uC744 \uC7AC\uB3C4\uC785

\uADDC\uCE59:
- \uCCAB \uBC88\uC9F8 \uB4F1\uC7A5\uC740 \uC720\uC9C0, \uC774\uD6C4 \uAC19\uC740 \uC544\uC774\uB514\uC5B4\uB294 \uC0AD\uC81C
- \uB2E4\uC2DC \uC4F0\uAC70\uB098 \uBC14\uAFB8\uC9C0 \uB9D0\uACE0 \uC0AD\uC81C\uB9CC \uD558\uC138\uC694
- \uC139\uC158 \uAD6C\uBD84\uC790(=== SECTION N: ... ===)\uB294 \uADF8\uB300\uB85C \uC720\uC9C0
- \uC139\uC158\uC774 \uBE44\uBA74 "(\uC55E \uC139\uC158\uC73C\uB85C \uD1B5\uD569\uB428)"\uC744 \uB0A8\uAE30\uC138\uC694
- \uC804\uCCB4 \uD14D\uC2A4\uD2B8\uB97C \uAD6C\uBD84\uC790 \uD3EC\uD568\uD574 \uCD9C\uB825\uD558\uC138\uC694

\uC5D0\uC138\uC774 \uBCF8\uBB38:
${fullBody}`;
  const modelMax = (_a = MODEL_MAX_OUTPUT[cfg.model]) != null ? _a : 4096;
  let cleaned;
  try {
    cleaned = await llmCall(cfg, SYS(lang), prompt, modelMax);
  } catch (e) {
    return sectionsWithHeadings.map((s) => s.body);
  }
  return sectionsWithHeadings.map((_, i) => {
    const n = i + 1;
    const nextN = i + 2;
    const start = cleaned.indexOf(`=== SECTION ${n}:`);
    if (start === -1) return sectionsWithHeadings[i].body;
    const headerEnd = cleaned.indexOf("\n", start);
    const end = cleaned.indexOf(`=== SECTION ${nextN}:`, start);
    const body = cleaned.slice(headerEnd + 1, end === -1 ? void 0 : end).trim();
    return body || sectionsWithHeadings[i].body;
  });
}
async function generateEssay(provider, apiKey, model, transcript, language, sourceTitle, quality, onProgress) {
  const cfg = { provider, apiKey, model };
  const qp = QUALITY_PARAMS[quality];
  const onStatus = (step) => onProgress({ step, current: 0, total: 100 });
  const outline = await buildOutline(cfg, transcript, language, sourceTitle, qp, onStatus);
  const totalSteps = outline.sections.length + 2;
  let done = 0;
  const tick = (step) => {
    done++;
    onProgress({ step, current: Math.round(done / totalSteps * 100), total: 100 });
  };
  tick(language === "en" ? "Writing introduction\u2026" : "\uC11C\uB860 \uC791\uC131 \uC911\u2026");
  const intro = await writeIntroOrConclusion(cfg, language, outline, "", "introduction");
  const bodies = [];
  for (let i = 0; i < outline.sections.length; i++) {
    tick(
      language === "en" ? `Writing section ${i + 1}/${outline.sections.length}: "${outline.sections[i].title}"` : `\uC139\uC158 ${i + 1}/${outline.sections.length} \uC791\uC131 \uC911: "${outline.sections[i].title}"`
    );
    const completed = outline.sections.slice(0, i).map((s) => ({
      title: s.title,
      summary: s.summary
    }));
    const text = await writeSection(cfg, language, outline, i, transcript, completed, qp);
    bodies.push(text);
  }
  onProgress({
    step: language === "en" ? "Reviewing for duplicate content\u2026" : "\uC911\uBCF5 \uB0B4\uC6A9 \uAC80\uD1A0 \uC911\u2026",
    current: 92,
    total: 100
  });
  const dedupedBodies = await deduplicateBody(
    cfg,
    language,
    outline.sections.map((s, i) => ({ heading: s.title, body: bodies[i] }))
  );
  tick(language === "en" ? "Writing conclusion\u2026" : "\uACB0\uB860 \uC791\uC131 \uC911\u2026");
  const conclusion = await writeIntroOrConclusion(
    cfg,
    language,
    outline,
    dedupedBodies.join("\n\n"),
    "conclusion"
  );
  const styleTag = language === "en" ? "AEON Essay" : "\uB274\uD544\uB85C\uC18C\uD37C \uC5D0\uC138\uC774";
  const now = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
  const safeTitle = outline.essayTitle.replace(/"/g, '\\"');
  const toc = outline.sections.map((s, i) => `${i + 1}. ${s.title}`).join("\n");
  const body = outline.sections.map((s, i) => `## ${s.title}

${dedupedBodies[i]}`).join("\n\n---\n\n");
  return `---
title: "${safeTitle}"
source: "${sourceTitle}"
generated: "${now}"
style: "${styleTag}"
language: "${language}"
provider: "${provider}"
model: "${model}"
---

# ${outline.essayTitle}

> *${styleTag} \u2014 based on: ${sourceTitle}*

## ${language === "en" ? "Contents" : "\uBAA9\uCC28"}

${toc}

---

${intro}

---

${body}

---

## ${language === "en" ? "Closing Reflection" : "\uB098\uC624\uBA70"}

${conclusion}

---

*${language === "en" ? "Source" : "\uCD9C\uCC98"}: ${sourceTitle} \xB7 ${now} \xB7 ${styleTag}*
`;
}

// src/modal.ts
var FileSuggestModal = class extends import_obsidian3.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder("Choose a transcript .md file\u2026");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};
var YoutubeEssayModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.selectedFile = null;
    this.isGenerating = false;
    this.progressBar = null;
    this.statusEl = null;
    this.fileNameEl = null;
    this.plugin = plugin;
    this.language = plugin.settings.defaultLanguage;
    this.quality = plugin.settings.defaultQuality;
    const active = this.app.workspace.getActiveFile();
    if (active && active.extension === "md") {
      this.selectedFile = active;
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "YouTube Essay Generator" });
    const fileSetting = new import_obsidian3.Setting(contentEl).setName("Transcript file").setDesc("Select the .md transcript file exported by YTranscript");
    this.fileNameEl = fileSetting.descEl.createEl("div");
    this.fileNameEl.style.cssText = "margin-top:4px; font-size:0.85em; color:var(--text-accent); font-weight:500;";
    this.updateFileLabel();
    fileSetting.addButton(
      (btn) => btn.setButtonText("Choose file\u2026").onClick(() => {
        new FileSuggestModal(this.app, (file) => {
          this.selectedFile = file;
          this.updateFileLabel();
        }).open();
      })
    );
    new import_obsidian3.Setting(contentEl).setName("Essay Style").addDropdown(
      (drop) => drop.addOption("ko", "\uD55C\uAD6D\uC5B4 \u2014 \uB274\uD544\uB85C\uC18C\uD37C \uC2A4\uD0C0\uC77C").addOption("en", "English \u2014 AEON style").setValue(this.language).onChange((v) => this.language = v)
    );
    new import_obsidian3.Setting(contentEl).setName("Quality / Cost").setDesc("\uC800\uBE44\uC6A9 \u2248 Haiku 10\uBD84/$0.01 | \uC911\uAC04 \u2248 $0.03\u20130.05 | \uACE0\uD488\uC9C8 \u2248 $0.08\u20130.15").addDropdown(
      (drop) => drop.addOption("quick", "\u26A1 \uC800\uBE44\uC6A9 \u2014 \uC9E7\uC740 \uC601\uC0C1, \uBE60\uB984").addOption("balanced", "\u2696\uFE0F \uC911\uAC04\uBE44\uC6A9 \u2014 \uADE0\uD615 (\uAE30\uBCF8)").addOption("thorough", "\u{1F50D} \uACE0\uD488\uC9C8 \u2014 \uAE34 \uC601\uC0C1, \uC0C1\uC138 \uCEE4\uBC84\uB9AC\uC9C0").setValue(this.quality).onChange((v) => this.quality = v)
    );
    this.statusEl = contentEl.createEl("p");
    this.statusEl.style.cssText = "color:var(--text-muted); font-size:0.85em; min-height:1.2em; margin:4px 0;";
    const progressWrap = contentEl.createEl("div");
    progressWrap.style.cssText = "height:4px; background:var(--background-modifier-border); border-radius:2px; margin:6px 0 12px; overflow:hidden;";
    this.progressBar = progressWrap.createEl("div");
    this.progressBar.style.cssText = "height:100%; width:0%; background:var(--interactive-accent); transition:width 0.4s ease;";
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Generate Essay").setCta().onClick(() => {
        if (!this.isGenerating) this.runGeneration();
      })
    );
  }
  updateFileLabel() {
    if (!this.fileNameEl) return;
    this.fileNameEl.setText(
      this.selectedFile ? `\u{1F4C4} ${this.selectedFile.path}` : "No file selected"
    );
  }
  setStatus(text, percent) {
    if (this.statusEl) this.statusEl.setText(text);
    if (this.progressBar && percent !== void 0) {
      this.progressBar.style.width = `${percent}%`;
    }
  }
  getApiKey() {
    const s = this.plugin.settings;
    switch (s.apiProvider) {
      case "claude":
        return s.claudeApiKey;
      case "openai":
        return s.openaiApiKey;
      case "gemini":
        return s.geminiApiKey;
    }
  }
  getModel() {
    const s = this.plugin.settings;
    switch (s.apiProvider) {
      case "claude":
        return s.claudeModel;
      case "openai":
        return s.openaiModel;
      case "gemini":
        return s.geminiModel;
    }
  }
  async runGeneration() {
    if (!this.selectedFile) {
      new import_obsidian3.Notice("Please select a transcript file first.");
      return;
    }
    const apiKey = this.getApiKey();
    if (!apiKey) {
      new import_obsidian3.Notice(
        `YouTube Essay Generator: Please add your ${this.plugin.settings.apiProvider} API key in Settings.`
      );
      return;
    }
    this.isGenerating = true;
    this.setStatus(this.language === "en" ? "Reading transcript\u2026" : "\uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8 \uC77D\uB294 \uC911\u2026", 2);
    try {
      const transcript = await this.app.vault.read(this.selectedFile);
      if (!transcript.trim()) {
        throw new Error("The selected file is empty.");
      }
      const sourceTitle = this.selectedFile.basename;
      this.setStatus(
        this.language === "en" ? `Transcript loaded (${transcript.length.toLocaleString()} chars). Generating essay\u2026` : `\uD2B8\uB79C\uC2A4\uD06C\uB9BD\uD2B8 \uB85C\uB4DC \uC644\uB8CC (${transcript.length.toLocaleString()}\uC790). \uC5D0\uC138\uC774 \uC0DD\uC131 \uC911\u2026`,
        5
      );
      const markdown = await generateEssay(
        this.plugin.settings.apiProvider,
        apiKey,
        this.getModel(),
        transcript,
        this.language,
        sourceTitle,
        this.quality,
        ({ step, current }) => this.setStatus(step, 5 + Math.round(current * 0.93))
      );
      await this.saveEssay(markdown, sourceTitle);
      this.setStatus(this.language === "en" ? "Essay saved!" : "\uC5D0\uC138\uC774 \uC800\uC7A5 \uC644\uB8CC!", 100);
      setTimeout(() => this.close(), 1800);
    } catch (err) {
      const msg = err.message;
      console.error("[YouTubeEssay]", err);
      new import_obsidian3.Notice(`Essay Generator Error: ${msg}`);
      this.setStatus(`Error: ${msg}`);
    } finally {
      this.isGenerating = false;
    }
  }
  async saveEssay(markdown, sourceTitle) {
    const folder = this.plugin.settings.outputFolder;
    if (folder && !this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
    const safeTitle = sourceTitle.replace(/[\\/:*?"<>|#^[\]]/g, "-").replace(/\s+/g, " ").trim().slice(0, 60);
    const styleSuffix = this.language === "en" ? "AEON" : "\uB274\uD544\uB85C\uC18C\uD37C";
    const timestamp = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const filename = `${folder ? folder + "/" : ""}${safeTitle} \u2014 ${styleSuffix} (${timestamp}).md`;
    const file = await this.app.vault.create(filename, markdown);
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(file);
    new import_obsidian3.Notice(`Essay saved: ${filename}`);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/main.ts
var YoutubeEssayPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "generate-youtube-essay",
      name: "Generate essay from YouTube video",
      callback: () => {
        if (!this.hasApiKey()) {
          new import_obsidian4.Notice(
            "YouTube Essay Generator: Please add an API key (Claude / OpenAI / Gemini) in the plugin settings."
          );
          return;
        }
        new YoutubeEssayModal(this.app, this).open();
      }
    });
    this.addRibbonIcon("film", "YouTube Essay Generator", () => {
      new YoutubeEssayModal(this.app, this).open();
    });
    this.addSettingTab(new YoutubeEssaySettingTab(this.app, this));
  }
  hasApiKey() {
    const s = this.settings;
    return !!(s.claudeApiKey || s.openaiApiKey || s.geminiApiKey);
  }
  onunload() {
  }
  async loadSettings() {
    const saved = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    this.settings = migrateSettings(saved);
    await this.saveData(this.settings);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
